image: node:20-slim

services:
  - docker:dind

variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_TLS_CERTDIR: ""
  # HEROKU_API_KEY: "key"

stages:
  - deploy

before_script:
  # 필수 패키지 설치
  - apt-get update && apt-get install -y curl bash docker.io
  # Heroku CLI 설치
  - curl https://cli-assets.heroku.com/install.sh | sh
  - heroku --version
  - docker --version

deploy:
  stage: deploy
  script:
    # Heroku CLI 로그인
    - export HEROKU_API_KEY=$HEROKU_API_KEY
    # - echo $HEROKU_API_KEY
    - heroku container:login
    # Docker 이미지 빌드
    - docker build -t registry.heroku.com/web-agency/web .
    # Docker 이미지 푸시
    - docker push registry.heroku.com/web-agency/web
    # Heroku 배포
    - heroku container:release web -a web-agency
  only:
    - master
